mod ofc;

fn main() {
    let testData = [
        [
            "3s",
            "3h",
            "3d",
            "5h",
            "6h",
            "7h",
            "8h",
            "9h",
            "Th",
            "Jh",
            "Qh",
            "Kh",
            "Ah"
        ],
        [
            "2s",
            "3s",
            "4s",
            "5s",
            "6s",
            "7s",
            "8s",
            "9s",
            "Ts",
            "Js",
            "Qs",
            "Ks",
            "As",
        ],
        [
            "2d",
            "3d",
            "4d",
            "5d",
            "6d",
            "7d",
            "8d",
            "9d",
            "Td",
            "Jd",
            "Qd",
            "Kd",
            "Ad"
        ],
    ];
    ofc::parse_input(testData);
}
